begin;

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  full_name text not null,
  email text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.places (
  place_id bigint generated by default as identity primary key,
  place_name text not null,
  description text not null,
  price_range text not null,
  budget text not null,
  rating numeric(3,1) not null default 0,
  place_address text not null,
  image_path text,
  activity_name text not null,
  city_name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists places_city_name_idx on public.places (city_name);
create index if not exists places_activity_name_idx on public.places (activity_name);
create index if not exists places_budget_idx on public.places (budget);
create index if not exists places_filter_combo_idx
  on public.places (city_name, budget, activity_name, place_id desc);
create index if not exists places_surprise_combo_idx
  on public.places (city_name, budget, rating desc, created_at desc);

create table if not exists public.reviews (
  review_id bigint generated by default as identity primary key,
  place_id bigint not null references public.places (place_id) on delete cascade,
  user_id text not null,
  name text not null,
  review_text text not null,
  rating int not null default 5,
  image text not null default '',
  created_at timestamptz not null default now()
);

alter table if exists public.reviews
  alter column user_id type text using user_id::text;

create index if not exists reviews_place_id_idx on public.reviews (place_id);
create index if not exists reviews_created_at_idx on public.reviews (created_at desc);
create index if not exists reviews_place_created_idx
  on public.reviews (place_id, created_at desc);
create index if not exists profiles_email_idx on public.profiles (email);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_places_set_updated_at on public.places;
create trigger trg_places_set_updated_at
before update on public.places
for each row
execute function public.set_updated_at();

drop trigger if exists trg_profiles_set_updated_at on public.profiles;
create trigger trg_profiles_set_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, email)
  values (
    new.id,
    coalesce(
      nullif(new.raw_user_meta_data->>'full_name', ''),
      nullif(new.raw_user_meta_data->>'name', ''),
      split_part(new.email, '@', 1)
    ),
    new.email
  )
  on conflict (id) do update
  set full_name = excluded.full_name,
      email = excluded.email,
      updated_at = now();

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_user();

insert into public.profiles (id, full_name, email)
select
  id,
  coalesce(
    nullif(raw_user_meta_data->>'full_name', ''),
    nullif(raw_user_meta_data->>'name', ''),
    split_part(email, '@', 1)
  ) as full_name,
  email
from auth.users
on conflict (id) do update
set full_name = excluded.full_name,
    email = excluded.email,
    updated_at = now();

alter table public.profiles enable row level security;
alter table public.places enable row level security;
alter table public.reviews enable row level security;

drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile"
on public.profiles
for select
using (auth.uid() = id);

drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own profile"
on public.profiles
for insert
with check (auth.uid() = id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
on public.profiles
for update
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "Public read places" on public.places;
create policy "Public read places"
on public.places
for select
using (true);

drop policy if exists "Public write places" on public.places;
drop policy if exists "Authenticated insert places" on public.places;
create policy "Authenticated insert places"
on public.places
for insert
to authenticated
with check (true);

drop policy if exists "Public read reviews" on public.reviews;
create policy "Public read reviews"
on public.reviews
for select
using (true);

drop policy if exists "Authenticated write reviews" on public.reviews;
create policy "Authenticated write reviews"
on public.reviews
for insert
to authenticated
with check (auth.uid()::text = user_id);

drop policy if exists "Authenticated delete reviews" on public.reviews;
create policy "Authenticated delete reviews"
on public.reviews
for delete
to authenticated
using (auth.uid()::text = user_id);

comment on table public.profiles is 'Authenticated user profiles synced from auth.users.';
comment on table public.places is 'Place listings are publicly readable. Inserts require an authenticated app user; admin mutations use the server-side service role.';
comment on table public.reviews is 'Authenticated review table linked to auth.users.';

commit;
