-- =============================================================================
-- 0043  admin_roles & audit_logs — canonical migration
-- -----------------------------------------------------------------------------
-- The tables below were previously only in supabase_admin_setup.sql (a
-- one-time manual script). That created an environment-parity risk: a fresh
-- database restored purely from migrations would be missing admin_roles,
-- making the dashboard inaccessible and security checks undefined.
--
-- This migration is fully idempotent:
--   • CREATE TABLE IF NOT EXISTS prevents failure if already created.
--   • DROP POLICY IF EXISTS + CREATE POLICY is the standard safe pattern.
--   • No data mutations — only DDL and policy definitions.
--
-- WARNING: Do NOT drop or revert this migration in production without first
-- ensuring admin access is preserved through another mechanism.
-- =============================================================================

begin;

-- ---------------------------------------------------------------------------
-- 1. admin_roles
-- ---------------------------------------------------------------------------
-- Stores the dashboard-level role for users who operate the admin panel.
-- A user can be in both public.user_roles (as 'user'/'provider') and here
-- (as 'admin'/'super_admin') — these are independent authority domains.
--
-- RLS is intentionally DISABLED: the dashboard always connects with the
-- service-role key (bypasses RLS anyway) and enabling RLS here would
-- create recursive-policy evaluation issues (checking admin_roles requires
-- reading admin_roles). The table is never exposed to the client-side auth
-- client.
-- ---------------------------------------------------------------------------
create table if not exists public.admin_roles (
  user_id   uuid primary key references auth.users(id) on delete cascade,
  role      text not null check (role in ('admin', 'super_admin')),
  created_at timestamptz not null default now()
);

-- Keep RLS disabled — dashboard uses service role key exclusively.
alter table public.admin_roles disable row level security;

-- Make sure any leftover policies from the old manual script are gone.
drop policy if exists "Admins can read admin_roles" on public.admin_roles;

-- ---------------------------------------------------------------------------
-- 2. audit_logs
-- ---------------------------------------------------------------------------
-- Tracks destructive or privileged dashboard actions for accountability.
-- Admins can read their own action history; writes go through server actions
-- that run with the service role, so no INSERT policy is needed for anon/auth.
-- ---------------------------------------------------------------------------
create table if not exists public.audit_logs (
  id         bigint generated by default as identity primary key,
  admin_id   uuid references auth.users(id) on delete set null,
  action     text        not null,
  table_name text        not null,
  record_id  text,
  created_at timestamptz not null default now()
);

alter table public.audit_logs enable row level security;

drop policy if exists "Admins can read audit_logs" on public.audit_logs;
create policy "Admins can read audit_logs"
  on public.audit_logs for select
  using (
    -- Only admins can read the audit log; checked by service role path anyway.
    exists (select 1 from public.admin_roles where user_id = auth.uid())
  );

-- ---------------------------------------------------------------------------
-- 3. index for audit log timeline queries
-- ---------------------------------------------------------------------------
create index if not exists audit_logs_admin_id_idx on public.audit_logs (admin_id);
create index if not exists audit_logs_created_at_idx on public.audit_logs (created_at desc);

-- ---------------------------------------------------------------------------
-- 4. Profile read policy for admins
-- ---------------------------------------------------------------------------
-- Admins need to read any profile for the users/providers/places pages.
-- Service-role access bypasses this but it is good defence-in-depth for
-- any future non-service-role dashboard calls.
-- ---------------------------------------------------------------------------
drop policy if exists "Admins can read all profiles" on public.profiles;
create policy "Admins can read all profiles"
  on public.profiles for select
  using (
    exists (select 1 from public.admin_roles where user_id = auth.uid())
  );

-- ---------------------------------------------------------------------------
-- 5. Places admin policies (idempotent re-declare)
-- ---------------------------------------------------------------------------
-- The old manual setup script added these; re-declaring them here keeps the
-- migration chain authoritative. We drop-and-recreate so the constraints
-- are exactly what this migration intends, not whatever happened to be set
-- by the manual script.
-- ---------------------------------------------------------------------------

drop policy if exists "Admins can insert places"  on public.places;
create policy "Admins can insert places"
  on public.places for insert
  with check (
    exists (select 1 from public.admin_roles where user_id = auth.uid())
  );

drop policy if exists "Admins can update places"  on public.places;
create policy "Admins can update places"
  on public.places for update
  using (
    exists (select 1 from public.admin_roles where user_id = auth.uid())
  );

drop policy if exists "Admins can delete places"  on public.places;
create policy "Admins can delete places"
  on public.places for delete
  using (
    exists (select 1 from public.admin_roles where user_id = auth.uid())
  );

-- ---------------------------------------------------------------------------
-- 6. Reviews admin policy
-- ---------------------------------------------------------------------------
drop policy if exists "Admins can delete any review"  on public.reviews;
create policy "Admins can delete any review"
  on public.reviews for delete
  using (
    exists (select 1 from public.admin_roles where user_id = auth.uid())
  );

commit;
