-- =============================================================================
-- 0044  Analytics integrity hardening
-- -----------------------------------------------------------------------------
-- Audit finding CRITICAL-01: insert_event_batch has no server-side rate
-- limiting — a malicious client can spam millions of fake events.
--
-- Audit finding CRITICAL-02: record_campaign_metric directly increments
-- counters without deduplication, rate limiting, or session uniqueness.
--
-- This migration:
--   1. Replaces insert_event_batch with a hardened version that:
--      • enforces a per-session burst limit (max 50 events / 60 s)
--      • validates provider_id ↔ place.provider_id when both are supplied
--      • strips future / far-past occurred_at values (cap: ±5 minutes)
--
--   2. Replaces record_campaign_metric with a hardened version that:
--      • records a raw impression/click event into campaign_metric_events
--        (deduplicatable) instead of directly incrementing counters
--      • keeps the direct-increment as a background rollup (done via
--        the insert trigger below so the counters stay fast for reads)
--
--   3. Adds campaign_metric_events table for raw event storage
--
-- NOTE: The counters on promotional_campaigns (impressions, clicks) are
-- preserved and kept up-to-date by the trigger. Existing data is intact.
-- =============================================================================

begin;

-- ---------------------------------------------------------------------------
-- 1. campaign_metric_events — raw event log (deduplication source)
-- ---------------------------------------------------------------------------
create table if not exists public.campaign_metric_events (
  id           bigint generated by default as identity primary key,
  campaign_id  uuid        not null references public.promotional_campaigns(id)
                           on delete cascade,
  metric       text        not null check (metric in ('impression', 'click')),
  session_id   uuid,                        -- NULL for anon calls
  user_id      uuid,                        -- NULL for anon calls
  occurred_at  timestamptz not null default now()
);

-- Index for deduplication window queries
create index if not exists cme_campaign_session_metric_idx
  on public.campaign_metric_events (campaign_id, metric, session_id, occurred_at desc);

create index if not exists cme_campaign_user_metric_idx
  on public.campaign_metric_events (campaign_id, metric, user_id, occurred_at desc);

-- RLS: anyone can insert (controlled by the RPC), service-role reads for rollup
alter table public.campaign_metric_events enable row level security;

drop policy if exists cme_no_direct_read   on public.campaign_metric_events;
drop policy if exists cme_no_direct_write  on public.campaign_metric_events;
create policy cme_no_direct_read  on public.campaign_metric_events for select using (false);
create policy cme_no_direct_write on public.campaign_metric_events for insert with check (false);
-- All access goes through SECURITY DEFINER RPCs.

-- ---------------------------------------------------------------------------
-- 2. Trigger: roll up raw events → promotional_campaigns counters
-- ---------------------------------------------------------------------------
create or replace function public._rollup_campaign_metric()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.metric = 'impression' then
    update public.promotional_campaigns
       set impressions = impressions + 1, updated_at = now()
     where id = new.campaign_id and status = 'active';
  elsif new.metric = 'click' then
    update public.promotional_campaigns
       set clicks = clicks + 1, updated_at = now()
     where id = new.campaign_id and status = 'active';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_rollup_campaign_metric on public.campaign_metric_events;
create trigger trg_rollup_campaign_metric
  after insert on public.campaign_metric_events
  for each row execute function public._rollup_campaign_metric();

-- ---------------------------------------------------------------------------
-- 3. Hardened record_campaign_metric
-- ---------------------------------------------------------------------------
-- Replaces the old direct-increment version.
-- Rate limiting: max 1 impression per (campaign, session, 60 min window)
--                max 1 click    per (campaign, session, 24 hour window)
-- Session_id is taken from the caller's auth claim when available, else
-- the supplied value.
-- ---------------------------------------------------------------------------
create or replace function public.record_campaign_metric(
  _campaign_id uuid,
  _metric      text,
  _session_id  uuid  default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  _uid        uuid := auth.uid();
  _sid        uuid := coalesce(_session_id, _uid);  -- fallback: use uid as dedup key
  _window     interval;
  _dup_count  int;
begin
  if _campaign_id is null or _metric is null then return; end if;
  if _metric not in ('impression', 'click') then return; end if;

  -- Deduplication window per metric type
  _window := case _metric
    when 'impression' then interval '60 minutes'
    when 'click'      then interval '24 hours'
    else interval '1 day'
  end;

  -- Check if the same session/user already fired this metric in the window
  if _sid is not null then
    select count(*)
      into _dup_count
      from public.campaign_metric_events
     where campaign_id  = _campaign_id
       and metric       = _metric
       and (session_id  = _sid or user_id = _sid)
       and occurred_at  > now() - _window;

    if _dup_count > 0 then return; end if;  -- deduplicated
  end if;

  -- Insert raw event; trigger rolls up to the counter column
  insert into public.campaign_metric_events
    (campaign_id, metric, session_id, user_id)
  select
    _campaign_id,
    _metric,
    _sid,
    _uid
  where exists (
    select 1 from public.promotional_campaigns
     where id = _campaign_id
       and status = 'active'
       and now() between starts_at and ends_at
  );
end;
$$;

-- Keep same grant: anon + auth can call the function (rate-limited inside)
revoke all on function public.record_campaign_metric(uuid, text, uuid) from public;
grant execute on function public.record_campaign_metric(uuid, text, uuid) to anon, authenticated;

-- Also revoke the old 2-arg overload so old clients can't bypass the dedup
-- by calling the signature directly. The trigger still works on existing data.
-- (Drop gracefully — might not exist if already replaced)
drop function if exists public.record_campaign_metric(uuid, text);

-- ---------------------------------------------------------------------------
-- 4. Hardened insert_event_batch
-- ---------------------------------------------------------------------------
-- New guarantees:
--   • occurred_at clamped to [now()-5min, now()+1min] — rejects replay attacks
--   • provider_id validated against place.provider_id when both are supplied
--   • Per-session burst cap: 50 events per 60-second window
-- ---------------------------------------------------------------------------
create or replace function public.insert_event_batch(_events jsonb)
returns int
language plpgsql
security definer
set search_path = ''
as $$
declare
  _uid            uuid := auth.uid();
  _inserted       int  := 0;
  _session_id     uuid;
  _burst_count    int;
  _burst_limit    constant int := 50;
  _burst_window   constant interval := interval '60 seconds';
  _time_tolerance constant interval := interval '5 minutes';
begin
  if _events is null or jsonb_typeof(_events) <> 'array' then
    return 0;
  end if;

  -- Extract session_id from first event for burst check
  _session_id := nullif((_events->0->>'session_id'), '')::uuid;

  -- Per-session burst rate limit (only meaningful when session_id is present)
  if _session_id is not null then
    select count(*)
      into _burst_count
      from public.analytics_events
     where session_id  = _session_id
       and occurred_at > now() - _burst_window;

    if _burst_count >= _burst_limit then
      return 0;  -- silently drop — don't reveal the limit to the client
    end if;
  end if;

  with raw as (
    select
      (e->>'kind')::public.analytics_event_kind                       as kind,
      nullif(e->>'place_id',    '')::uuid                             as place_id,
      nullif(e->>'provider_id', '')::uuid                             as provider_id,
      nullif(e->>'session_id',  '')::uuid                             as session_id,
      coalesce(e->'context',    '{}'::jsonb)                          as context,
      nullif(e->>'city_id',     '')::uuid                             as city_id,
      nullif(e->>'category_id', '')::uuid                             as category_id,
      -- Clamp occurred_at to a safe window around now() to prevent replay
      least(
        greatest(
          coalesce((e->>'occurred_at')::timestamptz, now()),
          now() - _time_tolerance
        ),
        now() + interval '1 minute'
      )                                                               as occurred_at
    from jsonb_array_elements(_events) as e
  ),
  validated as (
    select r.*
    from raw r
    where r.kind is not null
      -- When both place_id and provider_id are supplied, validate the pair.
      -- This prevents a client from attributing views to places it doesn't own.
      and (
        r.place_id is null
        or r.provider_id is null
        or exists (
          select 1 from public.places p
           where p.id          = r.place_id
             and p.provider_id = r.provider_id
        )
      )
  )
  insert into public.analytics_events
    (kind, place_id, provider_id, user_id, session_id, context,
     city_id, category_id, occurred_at)
  select
    kind, place_id, provider_id,
    _uid,
    session_id, context, city_id, category_id, occurred_at
  from validated;

  get diagnostics _inserted = row_count;
  return _inserted;
end;
$$;

-- Grants unchanged
revoke all on function public.insert_event_batch(jsonb) from public;
grant execute on function public.insert_event_batch(jsonb) to authenticated, anon;

commit;
